name: Build and Deploy to Azure
on:
  workflow_run:
    # Wait for CI Checks to complete before running
    workflows: ["CI Checks"]
    types:
      - completed

jobs:
  # Build Docker image and push to ACR
  build:
    # Needs to have CI Checks succeed and be on main branch
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Log in to Azure Container Registry
      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=sha-,format=short
            type=raw,value=latest,enable={{is_default_branch}}
            
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Deploy built image from ACR to Azure Container App
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get short SHA
        id: sha
        run: echo "short=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: 'my-ai-gaming-friend'
          containerAppName: 'myaigamingfriendcontainerjj'
          imageToDeploy: '${{ secrets.ACR_NAME }}.azurecr.io/${{ github.repository }}:sha-${{ steps.sha.outputs.short }}'
          registryUrl: ${{ secrets.ACR_NAME }}.azurecr.io
          registryUsername: ${{ secrets.ACR_USERNAME }}
          registryPassword: ${{ secrets.ACR_PASSWORD }}