name: Build and Deploy to Azure

on:
  workflow_run:
    # Wait for CI Checks to complete before running
    workflows: ["CI Checks"] 
    types:
      - completed
      
  workflow_dispatch:

jobs:
  # Build Docker image and push to ACR
  build:
    # Needs to have CI Checks succeed and be on main branch
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Log in to Azure to get access to ACR
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Deploy built image from ACR to Azure Container App
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: 'my-ai-gaming-friend'
          containerAppName: 'myaigamingfriendcontainerjj'
          # Point to the image in ACR using the commit SHA for the tag
          imageToDeploy: ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.repository }}:${{ github.sha }}