# .github/workflows/ci.yml

name: Run Python Tests

# This section defines the trigger for the workflow.
# It will run on every push to the 'main' branch,
# and on every pull request that targets the 'main' branch.
on:
  push:
  
  pull_request:
    branches: [ "main" ]

# A workflow is made up of one or more "jobs" that can run in parallel or sequence.
jobs:
  # This job is named "build". You can name it anything you like.
  build:
    # This specifies the type of virtual machine to run the job on.
    runs-on: ubuntu-latest

    # These are the steps the job will execute in order.
    steps:
      # Step 1: Check out your repository's code
      # This is a pre-built action that gives the job access to your code.
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up a specific version of Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install your project's dependencies
      # This command assumes you have a requirements.txt file.
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # This step also runs inside the ./backend folder
      - name: Run pytest
        working-directory: ./backend
        run: |
          pytest
